### ISSUE TITLE
redirect_to_info.php not accepting tokens

### ISSUE THREAD

**Issue by markus101** [rarbg/torrentapi#12]
Hello, I'm a dev on Sonarr and had a user report an issue with viewing the info of a torrent. I did some testing as outlined below, please let me know if I can provide any more details.

Using the `info_page` property from a search response I'm getting the message `Invalid token. Use get_token for a new one!` if I use `https://torrentapi.org/pubapi_v2.php?get_token=get_token` I get the same token in the URL and if I exclude the token I get an error stating I didn't include the token (`No token set!`).

**Comment by rarbg** [comment]
Fixed
Sorry about that

**Comment by markus101** [comment]
Thanks! Looks like everything is working now.
