### ISSUE TITLE
Your api not updating?

### ISSUE THREAD

**Issue by scriptzteam** [rarbg/torrentapi#14]
https://torrentapi.org/pubapi_v2.php?mode=list&token=SOMETOKENKEY

Always got only release {"torrent_results":[{"filename":"Victoria.S01E03.WEBRip.x264-RARBG","category":"TV and all older after that ...

**Comment by rarbg** [comment]
@scriptzteam 
What project are you from ?

**Comment by scriptzteam** [comment]
From NO project :D I am just lettin u know probably your cache not updating or broken db since its not updating?

**Comment by rarbg** [comment]
@scriptzteam 
if you dont read the first line of the api docs you just get shit banned and get no results

**Comment by scriptzteam** [comment]
If you do want to ban about 2,500,000 IPs then well lets see how it will works out xD

**Comment by rarbg** [comment]
@scriptzteam 
there are more than 10 mln ips that are banned. I dont see why adding 2.5mln more will be an issue

**Comment by rarbg** [comment]
@scriptzteam 
Oh and you obviously think im threatening you - im not. Learn to actually read. Read the first fucking line of the docs and actually pass an app id param to the api and you wont get shit banned. If you dont know what shit banned is you might know what a shadow ban is.

**Comment by scriptzteam** [comment]
Oh well nice now rarbg "You have experienced a bug in our site. An administrator has been notified about this problem. This page will automaticly refresh in 20 seconds."

rly thats great

**Comment by rarbg** [comment]
@scriptzteam 
just got hit with 400g , nothing major , 10 min downtime , thats all
not related to the API its separate
