### ISSUE TITLE
Sort by seeders causes incorrect or empty search results

### ISSUE THREAD

**Issue by erickok** [rarbg/torrentapi#2]
Please compare correct request for `search_string=archer` with `sort=last`
https://torrentapi.org/pubapi_v2.php?mode=search&search_string=archer&sort=last&format=json_extended&token=XXX
with `search_string=archer` with `sort=seeders`
https://torrentapi.org/pubapi_v2.php?mode=search&search_string=archer&sort=seeders&format=json_extended&token=XXX
or `search_string=house` with `sort=seeders`
https://torrentapi.org/pubapi_v2.php?mode=search&search_string=house&sort=seeders&format=json_extended&token=XXX

The first result (same as default sort) seems correct. The 2nd and 3rd return empty or only a small subset of results.

**Comment by rarbg** [comment]
@erickok 
I'll fix that , cant do it right now because ill need to do some reindexing.
However you can 
A) use category=tv param and it will show the correct results
or
B) use ranked=0 and it will show the correct results

**Comment by erickok** [comment]
Not sure if I understand. How does the sort order on number of seeders/leechers have an influence on which results are returned?

**Comment by rarbg** [comment]
It doesnt @erickok 
However if you read the docs :

By default the api will return only ranked torrents ( internal ) , scene releases + -rarbg releases + -rartv releases.
If you want other groups included in the results use the ranked parameter with a value of 0 to get them included.

Meaning , for the string you are searching there are no ranked results. Only uploaded by external groups.

**Comment by erickok** [comment]
Sure, okay. But the first two examples use the same query and both `ranked=1`, only a different sort order.

You are right that this problem does not occur for searches with `ranked=0`, it seems.

**Comment by rarbg** [comment]
I will correct the first 2 , dont worry about it :) Just use ranked=0 , anyways you are doing a search app , it should be ranked=0

**Comment by erickok** [comment]
:+1:
