### ISSUE TITLE
Rarbg Viewer

### ISSUE THREAD

**Issue by mancuniancol** [rarbg/torrentapi#5]
Hi, I want to inform that I've created a RARBg viewer for Kodi using the Api. I've tried to follow all the instruction.  Please, let me know if I need to do some adjustment.  The proyect is here:
https://github.com/mancuniancol/plugin.video.rarbg

**Comment by rarbg** [comment]
Hello
It looks good , however i think you should remove 
+                 'Movies/Full BD',
because Kodi cant stream those :)

**Comment by mancuniancol** [comment]
OK I will check it
